### ISSUE TITLE
[Feature Request] Compatibility with Sort Everything

### ISSUE THREAD

**Issue by GeographicCone** [Ferroxius/Smooth-GUI-for-Witcher-3-Complete-Edition#1]
In the spirit of the original mod, could you make an adaptation for compatibility with [Sort Everything](https://www.nexusmods.com/witcher3/mods/1710)?

The following files are changed by Sort Everything and would have to be readapted for 60 fps:

* `gameplay\gui_new\swf\alchemy\panel_alchemy.redswf`
* `gameplay\gui_new\swf\crafting\panel_crafting.redswf`
* `gameplay\gui_new\swf\glossary\panel_glossary_bestiary.redswf`
* `gameplay\gui_new\swf\glossary\panel_glossary_books.redswf`
* `gameplay\gui_new\swf\glossary\panel_glossary_tutorials.redswf`
* `gameplay\gui_new\swf\inventory\panel_inventory.redswf`
* `gameplay\gui_new\swf\journal\panel_journal_quests.redswf`

Thank you for your work, and for considering this request.

**Comment by Ferroxius** [comment]
I'll talk to Kovrik about using their files but no promises
